version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ./backend/.env

  agent:
    build:
      context: .
      dockerfile: ./agent/Dockerfile
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    env_file:
      - ./agent/.env
    volumes:
      - ./agent/autonome.config.json:/app/autonome.config.json:ro
    restart: unless-stopped

networks:
  default:
    name: agentic-ethereum
    driver: bridge
