services:
  chatbot:
    image: susumutomita/crypto-daily-brief-cdp-chatbot:latest
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CDP_API_KEY_NAME: ${CDP_API_KEY_NAME}
      CDP_API_KEY_PRIVATE_KEY: ${CDP_API_KEY_PRIVATE_KEY}
      NETWORK_ID: ${NETWORK_ID:-base-sepolia}
      GROQ_API_KEY: ${GROQ_API_KEY}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OLLAMA_ENDPOINT: ${OLLAMA_ENDPOINT}
      API_TARGET: ${API_TARGET}
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
